### ISSUE TITLE
AngularWormholeModule isnt found

### ISSUE THREAD

**Issue by svox1** [topaxi/angular-wormhole#1]
Hi,

thx for this nice plugin. Works like a charm.

The only problem is to get it to work with `yarn add` oder `npm install`. 
With `import { AngularWormholeModule } from 'angular-wormhole';` 
it doesnt finde the Module.

Did I need some type-declarations or is there a index.ts missed?

**Comment by topaxi** [comment]
What kind of setup are you using? WebPack? I have no `index.ts` file, the `angular-wormhole.module.ts` is defined as the main script in package.json (which should be picked up by WebPack).

**Comment by svox1** [comment]
I uses this Angular Seed Project:
https://github.com/mgechev/angular-seed/blob/2.1.2/README.md

**Comment by topaxi** [comment]
Fixed, released as v1.1.1

**Comment by svox1** [comment]
Hm, same problem. My Editor (IntelliJ) and the compiled version of my application cant finde the plugin.

For example, a other plugin works without any build configuration: `angular2-cookie` -> I didnt add this `'angular2-cookie': 'npm:angular2-cookie'` to my systemjs config.

**Comment by topaxi** [comment]
Is it possible that it is unable to find typescript files? The only difference I see in `angular2-cookie` that it ships compiled js files, while `angular-wormhole` only ships typescript.

**Comment by svox1** [comment]
Our project is written in Typescript. 

I think the different is that they have define some declare classes:
`core.d.ts`
With content:
`export * from './services';`

`service.d.ts`
```
export { BaseCookieOptions, CookieOptions } from './services/base-cookie-options';
export { CookieOptionsArgs } from './services/cookie-options-args.model';
export { CookieService } from './services/cookies.service';
```

If I removed this classes and the .d.ts files from services (without removing the files under ts) and changed my imports to ts:
`import { CookieService } from 'angular2-cookie/ts/services/cookies.service';`

The classes also didnt work. 

So I think only the typings are missed.

**Comment by svox1** [comment]
Here is an interesting point:
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript

And there is a change:
```
**Untyped imports**

TypeScript has traditionally been overly strict about how you can import modules. This was to avoid typos and prevent users from using modules incorrectly.

However, a lot of the time, you might just want to import an existing module that may not have its own .d.ts file. Previously this was an error. Starting with TypeScript 2.1 this is now much easier.

With TypeScript 2.1, you can import a JavaScript module without needing a type declaration. A type declaration (such as declare module "foo" { ... } or node_modules/@types/foo) still takes priority if it exists.

An import to a module with no declaration file will still be flagged as an error under --noImplicitAny.
```

I'am currently use 2.1.6. Maybe it works with 2.2.
